development:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['GOAL_DB'] %>
  username: <%= ENV['Nicolas Bermudez'] %>
  password: <%= ENV['mango1230'] %>
